
export enum UserRoles {
    GUEST = 'GUEST',
    CITTADINO_REGISTRATO = 'CITTADINO_REGISTRATO',
    OPERATORE_PROVIDER = 'OPERATORE_PROVIDER',
    RAPPRESENTANTE_LEGALE = 'RAPPRESENTANTE_LEGALE',
    RESPONSABILE_STRUTTURA = 'RESPONSABILE_STRUTTURA',
    ESECUTORE = 'ESECUTORE',
    ESECUTORE_SANITARIO = 'ESECUTORE_SANITARIO',
    ISPETTORE = 'ISPETTORE',
    FORMATORE_ISTRUTTORE = 'FORMATORE_ISTRUTTORE',
    DIRETTORE_CORSO = 'DIRETTORE_CORSO',
    ISTRUTTORE = 'ISTRUTTORE',
    ISTRUTTORE_SANITARIO = 'ISTRUTTORE_SANITARIO',
    NOR_RT = 'NOR_RT',
    _118 = '_118',
    RESPONSABILE_RT = 'RESPONSABILE_RT',
    RESPONSABILE_SICUREZZA = 'RESPONSABILE_SICUREZZA',
    COMPONENTE_FACULTY = 'COMPONENTE_FACULTY',
    DIRETTORE_SCIENTIFICO = 'DIRETTORE_SCIENTIFICO'
}
